version: '3'

   

services:

  web:

    build:

      context: .

      dockerfile: Dockerfile

    image: my-laravel-app

    ports:

      - "8080:80"

    volumes:

      - .:/var/www/html

      - ./.docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf